/**
 * Generated by orval v6.24.0 🍺
 * Do not edit manually.
 * wanaku-router API
 * OpenAPI spec version: 0.0.2-SNAPSHOT
 */
import * as axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";
export type PutApiV1ToolsRemoveParams = {
  tool?: string;
};

export type PutApiV1ResourcesRemoveParams = {
  resource?: string;
};

export type PutApiV1ManagementTargetsToolsUnlinkParams = {
  service?: string;
};

export type GetApiV1ManagementTargetsToolsList200 = { [key: string]: Service };

export type PutApiV1ManagementTargetsToolsLinkParams = {
  service?: string;
  target?: string;
};

export type PutApiV1ManagementTargetsToolsConfigureServiceParams = {
  option?: string;
  value?: string;
};

export type PutApiV1ManagementTargetsResourcesUnlinkParams = {
  service?: string;
};

export type PutApiV1ManagementTargetsResourcesLinkParams = {
  service?: string;
  target?: string;
};

export type PutApiV1ManagementTargetsResourcesConfigureServiceParams = {
  option?: string;
  value?: string;
};

export interface ToolReference {
  description?: string;
  inputSchema?: InputSchema;
  name?: string;
  type?: string;
  uri?: string;
}

export interface Service {
  configurations?: Configurations;
  target?: string;
}

export type GetApiV1ManagementTargetsResourcesList200 = {
  [key: string]: Service;
};

export interface Property {
  description?: string;
  type?: string;
}

export interface Param {
  name?: string;
  value?: string;
}

export interface ResourceReference {
  description?: string;
  location?: string;
  mimeType?: string;
  name?: string;
  params?: Param[];
  type?: string;
}

export type InputSchemaProperties = { [key: string]: Property };

export interface InputSchema {
  properties?: InputSchemaProperties;
  required?: string[];
  type?: string;
}

export interface Configuration {
  description?: string;
  value?: string;
}

export type ConfigurationsConfigurations = { [key: string]: Configuration };

export interface Configurations {
  configurations?: ConfigurationsConfigurations;
}

/**
 * @summary Resources Configure
 */
export const putApiV1ManagementTargetsResourcesConfigureService = <
  TData = AxiosResponse<void>,
>(
  service: string,
  params?: PutApiV1ManagementTargetsResourcesConfigureServiceParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(
    `/api/v1/management/targets/resources/configure/${service}`,
    undefined,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  );
};

/**
 * @summary Resources Link
 */
export const putApiV1ManagementTargetsResourcesLink = <
  TData = AxiosResponse<void>,
>(
  params?: PutApiV1ManagementTargetsResourcesLinkParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(
    `/api/v1/management/targets/resources/link`,
    undefined,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  );
};

/**
 * @summary Resources List
 */
export const getApiV1ManagementTargetsResourcesList = <
  TData = AxiosResponse<GetApiV1ManagementTargetsResourcesList200>,
>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(
    `/api/v1/management/targets/resources/list`,
    options,
  );
};

/**
 * @summary Resources Unlink
 */
export const putApiV1ManagementTargetsResourcesUnlink = <
  TData = AxiosResponse<void>,
>(
  params?: PutApiV1ManagementTargetsResourcesUnlinkParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(
    `/api/v1/management/targets/resources/unlink`,
    undefined,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  );
};

/**
 * @summary Tools Configure
 */
export const putApiV1ManagementTargetsToolsConfigureService = <
  TData = AxiosResponse<void>,
>(
  service: string,
  params?: PutApiV1ManagementTargetsToolsConfigureServiceParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(
    `/api/v1/management/targets/tools/configure/${service}`,
    undefined,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  );
};

/**
 * @summary Tools Link
 */
export const putApiV1ManagementTargetsToolsLink = <TData = AxiosResponse<void>>(
  params?: PutApiV1ManagementTargetsToolsLinkParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/v1/management/targets/tools/link`, undefined, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Tool List
 */
export const getApiV1ManagementTargetsToolsList = <
  TData = AxiosResponse<GetApiV1ManagementTargetsToolsList200>,
>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/v1/management/targets/tools/list`, options);
};

/**
 * @summary Tools Unlink
 */
export const putApiV1ManagementTargetsToolsUnlink = <
  TData = AxiosResponse<void>,
>(
  params?: PutApiV1ManagementTargetsToolsUnlinkParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(
    `/api/v1/management/targets/tools/unlink`,
    undefined,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  );
};

/**
 * @summary Expose
 */
export const postApiV1ResourcesExpose = <TData = AxiosResponse<void>>(
  resourceReference: ResourceReference,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(
    `/api/v1/resources/expose`,
    resourceReference,
    options,
  );
};

/**
 * @summary List
 */
export const getApiV1ResourcesList = <TData = AxiosResponse<void>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/v1/resources/list`, options);
};

/**
 * @summary Remove
 */
export const putApiV1ResourcesRemove = <TData = AxiosResponse<void>>(
  params?: PutApiV1ResourcesRemoveParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/v1/resources/remove`, undefined, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Add
 */
export const postApiV1ToolsAdd = <TData = AxiosResponse<void>>(
  toolReference: ToolReference,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.post(`/api/v1/tools/add`, toolReference, options);
};

/**
 * @summary List
 */
export const getApiV1ToolsList = <TData = AxiosResponse<void>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/api/v1/tools/list`, options);
};

/**
 * @summary Remove
 */
export const putApiV1ToolsRemove = <TData = AxiosResponse<void>>(
  params?: PutApiV1ToolsRemoveParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.put(`/api/v1/tools/remove`, undefined, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export type PutApiV1ManagementTargetsResourcesConfigureServiceResult =
  AxiosResponse<void>;
export type PutApiV1ManagementTargetsResourcesLinkResult = AxiosResponse<void>;
export type GetApiV1ManagementTargetsResourcesListResult =
  AxiosResponse<GetApiV1ManagementTargetsResourcesList200>;
export type PutApiV1ManagementTargetsResourcesUnlinkResult =
  AxiosResponse<void>;
export type PutApiV1ManagementTargetsToolsConfigureServiceResult =
  AxiosResponse<void>;
export type PutApiV1ManagementTargetsToolsLinkResult = AxiosResponse<void>;
export type GetApiV1ManagementTargetsToolsListResult =
  AxiosResponse<GetApiV1ManagementTargetsToolsList200>;
export type PutApiV1ManagementTargetsToolsUnlinkResult = AxiosResponse<void>;
export type PostApiV1ResourcesExposeResult = AxiosResponse<void>;
export type GetApiV1ResourcesListResult = AxiosResponse<void>;
export type PutApiV1ResourcesRemoveResult = AxiosResponse<void>;
export type PostApiV1ToolsAddResult = AxiosResponse<void>;
export type GetApiV1ToolsListResult = AxiosResponse<void>;
export type PutApiV1ToolsRemoveResult = AxiosResponse<void>;
