---
openapi: 3.1.0
paths:
  /api/v1/management/targets/resources/configure/{service}:
    put:
      parameters:
      - name: service
        in: path
        required: true
        schema:
          type: string
      - name: option
        in: query
        schema:
          type: string
      - name: value
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Resources Configure
      tags:
      - Targets Resource
  /api/v1/management/targets/resources/link:
    put:
      parameters:
      - name: service
        in: query
        schema:
          type: string
      - name: target
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Resources Link
      tags:
      - Targets Resource
  /api/v1/management/targets/resources/list:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: "#/components/schemas/Service"
      summary: Resources List
      tags:
      - Targets Resource
  /api/v1/management/targets/resources/unlink:
    put:
      parameters:
      - name: service
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Resources Unlink
      tags:
      - Targets Resource
  /api/v1/management/targets/tools/configure/{service}:
    put:
      parameters:
      - name: service
        in: path
        required: true
        schema:
          type: string
      - name: option
        in: query
        schema:
          type: string
      - name: value
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Tools Configure
      tags:
      - Targets Resource
  /api/v1/management/targets/tools/link:
    put:
      parameters:
      - name: service
        in: query
        schema:
          type: string
      - name: target
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Tools Link
      tags:
      - Targets Resource
  /api/v1/management/targets/tools/list:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: "#/components/schemas/Service"
      summary: Tool List
      tags:
      - Targets Resource
  /api/v1/management/targets/tools/unlink:
    put:
      parameters:
      - name: service
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Tools Unlink
      tags:
      - Targets Resource
  /api/v1/resources/expose:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResourceReference"
        required: true
      responses:
        "200":
          description: OK
      summary: Expose
      tags:
      - Resources Resource
  /api/v1/resources/list:
    get:
      responses:
        "200":
          description: OK
      summary: List
      tags:
      - Resources Resource
  /api/v1/resources/remove:
    put:
      parameters:
      - name: resource
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Remove
      tags:
      - Resources Resource
  /api/v1/tools/add:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ToolReference"
        required: true
      responses:
        "200":
          description: OK
      summary: Add
      tags:
      - Tools Resource
  /api/v1/tools/list:
    get:
      responses:
        "200":
          description: OK
      summary: List
      tags:
      - Tools Resource
  /api/v1/tools/remove:
    put:
      parameters:
      - name: tool
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
      summary: Remove
      tags:
      - Tools Resource
components:
  schemas:
    Configuration:
      type: object
      properties:
        value:
          type: string
        description:
          type: string
    Configurations:
      type: object
      properties:
        configurations:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Configuration"
    InputSchema:
      type: object
      properties:
        type:
          type: string
        properties:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/Property"
        required:
          type: array
          items:
            type: string
    Param:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    Property:
      type: object
      properties:
        type:
          type: string
        description:
          type: string
    ResourceReference:
      type: object
      properties:
        location:
          type: string
        type:
          type: string
        name:
          type: string
        description:
          type: string
        mimeType:
          type: string
        params:
          type: array
          items:
            $ref: "#/components/schemas/Param"
    Service:
      type: object
      properties:
        target:
          type: string
        configurations:
          $ref: "#/components/schemas/Configurations"
    ToolReference:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        uri:
          type: string
        type:
          type: string
        inputSchema:
          $ref: "#/components/schemas/InputSchema"
info:
  title: wanaku-router API
  version: 0.0.2-SNAPSHOT
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
